# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

r:
  - release

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

repos:
  docker: http://r.docker.stat.auckland.ac.nz/R

apt_packages:
  - libgtk2.0-dev
  - xorg-dev
  - libxml2-dev
  - libnlopt-dev
  - r-cran-rodbc
  - r-cran-rgtk2
  - r-cran-cairodevice

